### ISSUE TITLE
Add Livegrep results to the quickfix window

### ISSUE THREAD

**Issue by AW3i** [linrongbin16/fzfx.nvim#110]
Greetings and thanks for the great project!

I was looking for a way to add the results of the livegrep command when selecting mulitple items (and maybe as well from the find files one) to the quickfix window, to make operations on the list. Sadly I couldn't find a way to do that.

Is there any plans to implement this feature? 
I could also try to help with the implementation.

**Comment by linrongbin16** [comment]
It should be possible to add a user-defined action in [actions](https://github.com/linrongbin16/fzfx.nvim/blob/b6a7857d88aa50b61a1324f9326006b608e8c9b5/lua/fzfx/config.lua#L352) field in configuration.

Let me check how to add lines to quickfix window, I can implement it in `fzfx.actions`.

**Comment by linrongbin16** [comment]
PRs are welcome, you can check this PR: https://github.com/linrongbin16/fzfx.nvim/pull/112.

But the invoke of `setqflist` in this PR is wrong.

**Comment by damanis** [comment]
@linrongbin16 
There are worked versions of `setqflist` and `setqflist_rg` from PR [#112](https://github.com/linrongbin16/fzfx.nvim/pull/112)
```
local function parse_rg_qf_line(line)
    local splits = vim.fn.split(line, ":")
    print(vim.inspect(splits))
    local idx
    local res = {}
    if env.icon_enable() and vim.fn.split(splits[1], ' ')[2] then
        res.filename = vim.fn.split(splits[1], ' ')[2]
        idx = 2
    else
        res.filename = splits[1]
        idx = 1
    end
    res.line = splits[idx]
    idx = idx+1
    res.column = splits[idx]
    idx = idx+1
    res.text = splits[idx]
    return res
end

local function setqflist(lines)
    log.debug("|fzfx.actions - setqflist| lines:%s", vim.inspect(lines))
    local qflist = {}
    for _, line in ipairs(lines) do
        local filename = env.icon_enable() and vim.fn.split(line)[2] or line
        filename = path.normalize(filename)
        table.insert(qflist, {
	    filename = filename,
	    lnum = 1,
	    col = 1,
        })
    end
    log.debug("|fzfx.actions - setqflist| list:%s", vim.inspect(qflist))
    vim.fn.setqflist({}, " ", {
        nr = "$",
	items = qflist,
	-- title
    })
end

local function setqflist_rg(lines)
    log.debug("|fzfx.actions - setqflist_rg| lines:%s", vim.inspect(lines))
    local qflist = {}
    for _, line in ipairs(lines) do
	local item = parse_rg_qf_line(line)
        log.debug(
            "|fzfx.actions - setqflist_rg| qf item:%s",
            vim.inspect(item)
        )
        item.filename = path.normalize(item.filename)
        table.insert(qflist, {
	    filename = item.filename,
	    lnum = item.line,
	    col = item.column,
	    text = item.text
        })
    end
    log.debug("|fzfx.actions - setqflist_rg| list:%s", vim.inspect(qflist))
    -- local title = make_wf_title // [FZFX] <command> <search request>
    vim.fn.setqflist({}, " ", {
        nr = "$",
	items = qflist,
	-- title
    })
end
```

**Comment by linrongbin16** [comment]
hi, really thanks for sharing. 

this ticket is pending so long, I had try to implement `setqflist` several times but there are some other issues so I didn't do it. 

I will check this code first!!!

**Comment by linrongbin16** [comment]
I want to ask 1 more question about how you use setqflist? is it an action (will exit fzf) or an interaction that won't exit fzf?

1. select some lines, press `ctrl-q` to exit fzf, and send these lines to `setqflist` or `setqflist_rg` callbacks.
2. or just press `ctrl-q` and won't exit fzf, and send the current line to the callbacks?

**Comment by linrongbin16** [comment]
> I didn't add title (it shown in commands such as :colder or :cnewer) - need to parse additional parameters, current command name and current query, not line only.

let me see if I can pass sosme more data to the context.

**Comment by damanis** [comment]
> I want to ask 1 more question about how you use setqflist? is it an action (will exit fzf) or an interaction that won't exit fzf?
> 
> 1. select some lines, press `ctrl-q` to exit fzf, and send these lines to `setqflist` or `setqflist_rg` callbacks.
> 2. or just press `ctrl-q` and won't exit fzf, and send the current line to the callbacks?

In my opinion, exit is make sense.

**Comment by damanis** [comment]
I forgot to add call `copen` after vim.fn.setqflist.

**Comment by damanis** [comment]
> > I didn't add title (it shown in commands such as :colder or :cnewer) - need to parse additional parameters, current command name and current query, not line only.
> 
> let me see if I can pass sosme more data to the context.

@linrongbin16, I think in `setqflis_rg` enough pass only search pattern. Since `setqflist_rg` called from one of the varieties of LiveGrep, the title may be `[FZFX] live_grep <pattern>`.

**Comment by linrongbin16** [comment]
Hi @damanis , I checked the neovim doc about [setqflist](https://neovim.io/doc/user/builtin.html#setqflist()), but it still looks confusing to me.

especially this part:

```
                When {what} is not present, the items in {list} are used.  Each
		item must be a dictionary.  Non-dictionary items in {list} are
		ignored.  Each dictionary item can contain the following
		entries:
		    bufnr	buffer number; must be the number of a valid
				buffer
		    filename	name of a file; only used when "bufnr" is not
				present or it is invalid.
		    module	name of a module; if given it will be used in
				quickfix error window instead of the filename.
		    lnum	line number in the file
		    end_lnum	end of lines, if the item spans multiple lines
		    pattern	search pattern used to locate the error
		    col		column number
		    vcol	when non-zero: "col" is visual column
				when zero: "col" is byte index
		    end_col	end column, if the item spans multiple columns
		    nr		error number
		    text	description of the error
		    type	single-character error type, 'E', 'W', etc.
		    valid	recognized error message
		    user_data
				custom data associated with the item, can be
				any type.
```

I read your source code:

```lua
local function setqflist(lines)
    local qflist = {}
    for _, line in ipairs(lines) do
        local filename = env.icon_enable() and vim.fn.split(line)[2] or line
        filename = path.normalize(filename)
        table.insert(qflist, {
	    filename = filename,
	    lnum = 1,
	    col = 1,
        })
    end
    vim.fn.setqflist({}, " ", {
        nr = "$",
	items = qflist,
	-- title
    })
end
```

But I don't understand the `nr="$"` part, why the `nr` is not inside of `qflist` as a field in each item of the lua hash table?

**Comment by linrongbin16** [comment]
I made a screen recording with this commit: https://github.com/linrongbin16/fzfx.nvim/pull/290/commits/3860ead85a8564233c43130f4126bbf8e81eacf2.

It looks working now (prepend a `copen` command):

https://github.com/linrongbin16/fzfx.nvim/assets/6496887/c78b87bb-3e87-458e-8934-fd8153fd4354

**Comment by damanis** [comment]
@linrongbin16 
> But I don't understand the nr="$" part, why the nr is not inside of qflist as a field in each item of the lua hash table?
I passed qflist in third argument, `what`, not in first. In `what` `nr` is not part of qlist.

**Comment by linrongbin16** [comment]
got it, anyway it works ;) so it should be good, maybe let's refactor it after we have more knowledge.
