### ISSUE TITLE
Is there a way to setup `default_fzf_options`?

### ISSUE THREAD

**Issue by leoatchina** [linrongbin16/fzfx.nvim#129]
I prefer using  `c-d`/`c-u` to do half pagedown/pageup and planned to use m-x to delete buffer when using `fzfx.nvim` , but after previewing `config.lua`,  since I am familiar with language lua, I could found a quick way to change `default_fzf_options`. Would you tell me how or update the configuration script ? 

Now I am using `fzf-lua` in UNIX, and this plugin has  `lsp related symbols` commands, since `Lsp_diagnostics` has been finished, is `symbols` on the schedule ?

**Comment by linrongbin16** [comment]
Hi, you can configure the keys in `setup` function, please see: https://github.com/linrongbin16/fzfx.nvim#%EF%B8%8F-configuration

**Comment by linrongbin16** [comment]
lsp symbols is under development.

**Comment by linrongbin16** [comment]
oh, I think I understand your point, for now there's no way to batch configure all the preview page up/down keys.

You have to repeat now.

 I may think about how to let people batch configure them.

**Comment by leoatchina** [comment]
yes , batch configure is what I want.

**Comment by linrongbin16** [comment]
It will needs a more complicated opts merge policy, I think I can do it.

**Comment by linrongbin16** [comment]
Hi @leoatchina , I'm refactoring the default fzf opts, to allow you easier overwrite it.

see #130

**Comment by linrongbin16** [comment]
BTW, I set `ctrl-f` to scroll preview page down to avoid conflict with `ctrl-d` in `FzfxBuffers` command to delete buffer.

**Comment by leoatchina** [comment]
> 

yes, I have found lots of plugins use `c-f/b` to do pageup/down in fuzzy_finder/lsp_finder's popup windows, but In my workflow, `c-d` is used to do page scroll, so I need to change it.

**Comment by leoatchina** [comment]
But, I found `ctrl-u` is also mapped, so I think default map is also acceptable.

**Comment by linrongbin16** [comment]
close for issue resolve

**Comment by linrongbin16** [comment]
> Now I am using fzf-lua in UNIX, and this plugin has lsp related symbols commands, since Lsp_diagnostics has been finished, is symbols on the schedule ?

Hi @leoatchina , I had implement the `lsp_definitions` command in #150 , feel free to try and give me feedbacks!
