### ISSUE TITLE
FzfxGfiles bug.

### ISSUE THREAD

**Issue by leoatchina** [linrongbin16/fzfx.nvim#137]
both opend in a same file. you can see what's wrong. `FzfxGfile` only send files in current dir back

FzfGfiles
![image](https://github.com/linrongbin16/fzfx.nvim/assets/4470821/589d06c0-e96a-45bd-835d-4b4dd7378e8d)

FzfxGfiles
![image](https://github.com/linrongbin16/fzfx.nvim/assets/4470821/7237c458-920b-44c1-825f-7d4277b80196)

**Comment by linrongbin16** [comment]
Hi, @leoatchina, the default fzf opts of this plugin is different.

You can configure it here: https://github.com/linrongbin16/fzfx.nvim/blob/24389d67d9258bc7d05b39973e86b316e34290ba/lua/fzfx/config.lua#L1199.

It should be the `--layout` option

**Comment by linrongbin16** [comment]
Do you have `DEFAULT_FZF_OPTS` environment?  maybe I should respect this env var.

**Comment by leoatchina** [comment]
I my vim config ,  the preview windows postion is smartly adjusted
```
    let $FZF_DEFAULT_OPTS = '--layout=reverse-list --info=inline'
    if has('nvim') || has('patch-8.2.191')
        function s:fzf_updata_position()
            if &columns > &lines * 3
                let g:fzf_layout = {
                    \ 'window': {'width': 0.9, 'height': 0.8, 'border': 'sharp'}
                    \ }
                let g:fzf_preview_window = ['right,45%', '?']
            else
                let g:fzf_layout = {
                    \ 'window': {'width': 0.9, 'height': 0.6, 'border': 'sharp'}
                    \ }
                let g:fzf_preview_window = ['up,30%', '?']
            endif
            " NOTE: adjust vista_fzf_preview here
            let g:vista_fzf_preview = g:fzf_preview_window[0:0]
        endfunction
        call s:fzf_updata_position()
        au VimResized * call s:fzf_updata_position()
    else
        let g:fzf_layout = {'down': '~30%'}
        let g:fzf_preview_window = ['right,45%', '?']
    endif
```

**BUT** this is not the key point,  please notice `FzfxGitfiles` only send files in the **current dir** back

**Comment by linrongbin16** [comment]
let me check `FzfGFiles` implementation later.

**Comment by leoatchina** [comment]
Yep,  And   `FzfxProjectFiles` is recommended. You can see what I have set in my config
```
    " files search
    function! s:files_search()
        if get(g:, 'coc_git_status', '') != '' || !empty(GitRootPath())
            FzfGitFiles
        else
            lcd %:p:h
            FzfFiles
        endif
    endfunction
    command! FzfProjectFiles call s:files_search()
    nnoremap <silent><leader>fp :FzfProjectFiles<Cr>
```

**Comment by linrongbin16** [comment]
Hi @leoatchina, this issue is quite strange. would you please pull latest main branch and try again?

**Comment by leoatchina** [comment]
The path is  `~/.leovim.conf/cfg/vim`, where my vimscripts layed
`git ls-files` in neovim
![image](https://github.com/linrongbin16/fzfx.nvim/assets/4470821/ce6829d8-7c15-4ff8-99bf-4e112b212d6d)

in shell ,  I think this issue is related with $PWD in neovim
![image](https://github.com/linrongbin16/fzfx.nvim/assets/4470821/7cf56904-2e19-4d29-9771-0b1d75bfb9b4)

`git ls-files` only return files under current only

**Comment by linrongbin16** [comment]
yeah, you're right, the `FzfxGFiles` should be running in the git repo's root directory.

Thanks for education! I will fix it.

**Comment by linrongbin16** [comment]
Hi @leoatchina , I fixed this issue in #164 , but for now it's not merged into main branch.

Would you please try `linrongbin16/migrate-gfiles` branch?

**Comment by leoatchina** [comment]
Sorry for reply later, yes it works

**Comment by linrongbin16** [comment]
thanks! the implementation is somehow different with fzf.vim, but I think my implementation is more makes sense
