### ISSUE TITLE
推荐快捷键太多了，建议缩减一些。

### ISSUE THREAD

**Issue by sunshe35** [linrongbin16/fzfx.nvim#157]
如标题。
我处理这些快捷键处理了2小时，感觉有些快捷键根本没必要。
建议快捷键分成两部分，第一部分是推荐（只提供重要功能的快捷键），第二部分是可选。

**Comment by linrongbin16** [comment]
嗯，其实有了切换的快捷键之后，只需要normal, visual, cword, put 这四种按键就行了。

有时间可以改下readme

**Comment by linrongbin16** [comment]
Fixed in #152
