### ISSUE TITLE
setup| error! failed to find 'fzfx.nvim' plugin!

### ISSUE THREAD

**Issue by tssm** [linrongbin16/fzfx.nvim#437]
Hey! I've wanted to try this plug-in for a while, but I kept getting the following error immediately after launching Neovim:

```
E5113: Error while calling lua chunk: ...share/nvim/site/pack/plugins/start/fzfx/lua/fzfx/log.lua:153: |fzfx.module - setup| error! failed to find 'fzfx.nvim' plugin!
stack traceback:
	[C]: in function 'error'
	...share/nvim/site/pack/plugins/start/fzfx/lua/fzfx/log.lua:153: in function 'throw'
	...share/nvim/site/pack/plugins/start/fzfx/lua/fzfx/log.lua:161: in function 'ensure'
	...re/nvim/site/pack/plugins/start/fzfx/lua/fzfx/module.lua:87: in function 'setup'
	...cal/share/nvim/site/pack/plugins/start/fzfx/lua/fzfx.lua:33: in function <...cal/share/nvim/site/pack/plugins/start/fzfx/lua/fzfx.lua:7>
```

My understanding of [the code](https://github.com/linrongbin16/fzfx.nvim/blob/3199999e9f1a9d2ba55c73c80dcd0a3c90d3a835/lua/fzfx/module.lua#L65) is that the location of FZFX itself should being assigned to an environment variable, but for some reason it fails on my set-up. I presume that it's related to the way I'm installing it: I don't use a plug-in manager, instead I manage them with Nix, however I get the error even if I install it by cloning the repository in `~/.local/share/nvim/site/pack/whatever/start`, which is pretty standard. Any thoughts?

Thanks in advance! I can't wait to try it, looks pretty awesome!

**Comment by linrongbin16** [comment]
hi @tssm , I'm using this (https://github.com/linrongbin16/fzfx.nvim/pull/438/files) minimal init lua file to try to re-produce this issue.

Here's my working directory:

```
# the local fzfx.nvim plugin directory:
$HOME/github/linrongbin16/test/fzfx.nvim
```

<img width="433" alt="image" src="https://github.com/linrongbin16/fzfx.nvim/assets/6496887/58ddecf4-3ed2-454e-9bed-531276d479a3">

And neovim pack:

```
# the pack/*/start directory:
$HOME/.local/share/nvim/site/pack/test/start
```

<img width="788" alt="image" src="https://github.com/linrongbin16/fzfx.nvim/assets/6496887/d7094adc-8165-4728-a03e-eb71a0d94beb">

**Comment by linrongbin16** [comment]
> Thanks for the help! ❤️ By following your Instructions I found the issue: I dropped the `.nvim` suffix from the root directory, I should have figured this out by myself, sorry 🙈
> 
> But now that I have your attention, a quick question: Looks like the FZF dependency is there only to make sure that the binary is on the system, right? So it should work without that dependency as long as I make sure FZF is installed on my system?

it could be. but I didn't test it, you can try remove the dependency.

**Comment by tssm** [comment]
Oh, I just realized it's mandatory. I thought I had it working without it. No worries, it's fine. Thanks again!
