### ISSUE TITLE
bug: FzfxFileExplorer -> Cannot cd into a directorie with ALT-L on mac

### ISSUE THREAD

**Issue by nstirnemann7** [linrongbin16/fzfx.nvim#490]
Its how the title says, if I press ALT-l nothing happens, if I press ALT-L = Ò, that symbol appears, the easy solution would be to change the keymaps, but i dont find in the config how to change the default keymaps for FzfxFileTree

<img width="1331" alt="image" src="https://github.com/linrongbin16/fzfx.nvim/assets/104640386/59117ea0-7b33-4b31-a6dc-c0224d80b01c">

After pression ALT-SHIFT-L

<img width="1300" alt="image" src="https://github.com/linrongbin16/fzfx.nvim/assets/104640386/0d91ab9d-8efb-4f2a-9a3a-83d768476689">

After pressing ALT-l

<img width="1359" alt="image" src="https://github.com/linrongbin16/fzfx.nvim/assets/104640386/3d5cffd9-8437-4f14-ba32-c79a68485910">

System : Latest Macos
Using : lsd in replacement of ls
Neovim Version : nightly
Plugin Manager: Lazy
Config for fzxf: don't pass any opts

On WSL works as intended

**Comment by linrongbin16** [comment]
hi @nstirnemann7, I am not in front of my keyboard now, will check later.

**Comment by linrongbin16** [comment]
hi @nstirnemann7 , you can use below config (use `CTRL-L` to cd into, use `CTRL-H` to go upper):

```lua
require('fzfx').setup({
    file_explorer = {
        interactions = {
            cd = {
                key = "ctrl-l",
            },
            upper = {
                key = "ctrl-h",
            },
        },
    },
})
```

**Comment by nstirnemann7** [comment]
> hi @nstirnemann7 , you can use below config (use `CTRL-L` to cd into, use `CTRL-H` to go upper):
> 
> ```lua
> require('fzfx').setup({
>     file_explorer = {
>         interactions = {
>             cd = {
>                 key = "ctrl-l",
>             },
>             upper = {
>                 key = "ctrl-h",
>             },
>         },
>     },
> })
> ```
> 
> Based on different terminal app (iterm2 on macOS, Windows Terminal on Windows, gnome terminal on ubuntu gnome, and others like wezterm, alacritty, kitty), some `ctrl`/`alt` keys could be override by terminal app.
> 
> (It's true that this plugin's `configs` is quite complicated), you can refer to:
> 
> https://github.com/linrongbin16/fzfx.nvim/blob/be08a3006551843cf273184c89233e5114d8a21b/lua/fzfx/cfg/file_explorer.lua?plain=1#L288-L299

This Works! Thanks! I assume this problem happen in the mayority of 60% percentege keyboards, where random combinations give you symbols or glyphs because the keyboard is too short (ALT-l = ¬) (ALT-h = ˙)

**Comment by nstirnemann7** [comment]
Resolved!
