### ISSUE TITLE
Center search result once selected

### ISSUE THREAD

**Issue by savchenko** [linrongbin16/fzfx.nvim#493]
Small, but handy feature. When user selects a line from the Grep menu, execute `zz` on file.

Currently it moves cursor to the correct line, however it's not centred on the screen which makes it hard(er) to quickly find the cursor position.

**Comment by linrongbin16** [comment]
hi @savchenko, is it relate to this issue: https://github.com/linrongbin16/fzfx.nvim/issues/426

**Comment by linrongbin16** [comment]
hi @savchenko  thanks for suggestion, it seems a good feature.
