### ISSUE TITLE
invalid key: fzf_opts

### ISSUE THREAD

**Issue by savchenko** [linrongbin16/fzfx.nvim#494]
Using the official config, `--disabled` flag is just to test if it works:

```lua
-- Hotkeys
vim.keymap.set(
  "n",
  "<C-f>",
  "<cmd>FzfxFiles<cr>",
  {
    silent = true, noremap = true, desc = "Search files",
    fzf_opts = { "--disabled" }
  }
),
```

As per documentation:

> each commands group also has a 'fzf_opts' field that can overwrite this.

~~Am I missing something?~~ Clearly, passing this as a parameter for `vim.keymap.set()` is a bad idea... What's the right way?

**Comment by linrongbin16** [comment]
hi @savchenko, please refer to issue #495
