### ISSUE TITLE
Automatically resize buffer selection window

### ISSUE THREAD

**Issue by savchenko** [linrongbin16/fzfx.nvim#495]
Buffer names are usually comparatively short and don't require a preview.

I have implemented it via `fzf.vim` ages ago:

```vim
function! FZFBufFloat() abort
    let l:blengths = []
    for l:buffer in getbufinfo({'buflisted': 1})
        if empty(l:buffer.name)
            continue
        endif
        let l:buffer = substitute(shellescape(l:buffer.name),
              \ getcwd()."/", "", "")
        let l:buffer = substitute(l:buffer, $HOME, "~", "")
        call add(l:blengths, strchars(l:buffer))
    endfor
    return { 'width': max(l:blengths)+17, 'height':
          \ len(l:blengths)+6, 'yoffset': 0.5, 'border': 'rounded' }
endfunction

command! -bang -nargs=? -complete=dir Buffers call
      \ fzf#vim#buffers(<q-args>, {'options': '--padding=1',
      \ 'window': FZFBufFloat()}, <bang>0)
```

Would it be possible to have something like this in `fzfx.nvim` in Lua?

**Comment by linrongbin16** [comment]
hi @savchenko ,

The code looks like doing below things:
1. add `--padding=1` option to fzf binary.
2. adjust `width`, `height`, `border`, `rounded` options for `--preview-window` option.

If all the code is going to setting the options directly pass to fzf binary, then it could be done via the `fzf_opts` option (the only difference is written by lua), please see:

1. `FzfxBuffers` command default `fzf_opts` option: https://github.com/linrongbin16/fzfx.nvim/blob/be08a3006551843cf273184c89233e5114d8a21b/lua/fzfx/cfg/buffers.lua#L158-L165

**Comment by linrongbin16** [comment]
because 'win_opts' doesn't support function.

**Comment by linrongbin16** [comment]
> After further investigation, this works:
> 
> ```lua
> buffers = {
>   fzf_opts = {
>     "--info=hidden --header= --preview-window=hidden --padding=1"
>   },
>   win_opts = {
>         relative = 'win',
>         height = 10,
>         width = 40,
>         border = "rounded",
>         zindex = 51,
>     }
> }
> ```
> 
> However, this does not:
> 
> ```lua
> buffers = {
>   fzf_opts = {
>     "--info=hidden --header= --preview-window=hidden --padding=1"
>   },
>   win_opts = function()
>     local blengths = {}
>     local max_length = 0
>     for _, buffer_number in ipairs(vim.api.nvim_list_bufs()) do
>       local buffer_object = vim.api.nvim_buf_get_name(buffer_number)
>       local buffer_name = vim.fn.expand(buffer_object)
>       buffer_name = vim.fn.substitute(buffer_name, vim.fn.getcwd(), "", "g")
>       buffer_name = vim.fn.substitute(buffer_name, vim.fn.expand("$HOME"), "~", "g")
>       blengths[#blengths + 1] = vim.fn.strwidth(buffer_name)
>     end
>     for _, length in ipairs(blengths) do
>       max_length = math.max(max_length, length)
>     end
>     return {
>       border = "rounded",
>       height = #blengths + 4,
>       width = max_length + 4,
>       relative = 'win',
>       zindex = 51,
>     }
>   end
> }
> ```
> 
> Any idea why? The function returns correctly.

After carefully read your `win_opts` function, I think it's trying to calculate current buffer list size (for example 8), and then returns the `8` as the fzfx popup window's height.

Is that correct?

**Comment by linrongbin16** [comment]
hi @savchenko, current engine doesn't support real-time refresh the 'win_opts'.

for example, when 1st run `FzfxBuffers`, the height is `8`, max buffer name length is `36`. (we have 8 buffers, and max buffer name length is 36).

in the 1st fzfx popup, if you press some 'ctrl-d' keys and delete some buffers, the 'win_opts' will not be calculate again and refresh the 1st fzfx popup.

but after you press `esc` key and quit 1st popup, then run the 2nd `FzfxBuffers`, now the height and width will be calculate by the current buffers status.

I will submit PR to support the 'win_opts' to be a function, but it still cannot support the real-time scenario when you press 'ctrl-d' key.

**Comment by linrongbin16** [comment]
hi @savchenko , this feature is added in #517 , please pull latest main branch and have a try.
