### ISSUE TITLE
Allow selectively disabling header

### ISSUE THREAD

**Issue by savchenko** [linrongbin16/fzfx.nvim#505]
Passing `--header=` to `fzf_opts` clears the header content, but does not remove the blank line after the prompt:

![image](https://github.com/linrongbin16/fzfx.nvim/assets/300146/7f983d63-4505-48f9-aef3-281a59a5a920)

Perhaps allow its removal?

**Comment by linrongbin16** [comment]
hi @savchenko , would you tell me, which command are your trying to remove `--header` option?
