### ISSUE TITLE
Unify hotkeys in `FzfxFileExplorer`

### ISSUE THREAD

**Issue by savchenko** [linrongbin16/fzfx.nvim#506]
I propose to replace `alt` with `ctrl` here:

https://github.com/linrongbin16/fzfx.nvim/blob/e72c48659b0b856795b885ad9e84a32dc42ec11c/lua/fzfx/cfg/file_explorer.lua#L287-L297

This will allow unified <kbd>Ctrl</kbd>+<kbd>HJKL</kbd> in the file explorer.

Tested locally, works as expected.

**Comment by linrongbin16** [comment]
hi @savchenko , this is updated in https://github.com/linrongbin16/fzfx.nvim/pull/510, please pull latest main branch and try.
