### ISSUE TITLE
Expose command and search history, marks, etc.

### ISSUE THREAD

**Issue by savchenko** [linrongbin16/fzfx.nvim#523]
Meta-issue about implementing [commands](https://github.com/junegunn/fzf.vim#commands) from the original `fzf.vim`.

Some of the most important ones:

- [x] `:marks` in current and all opened files.
- [x] Command history (<kbd>Ctrl+F</kbd> in `:`)
- [ ] File history (`:bro ol`)
- [ ] Search history
- [ ] File types (`:set ft=`)

Thoughts?

**Comment by linrongbin16** [comment]
yes, I would re-wtite them from fzf.vim, one by one.

**Comment by linrongbin16** [comment]
> @linrongbin16 , do you want any input on the above? I'd be happy to help.

sure, I am now trying to implement the nvim builtin buffer previewer, it's super difficult, and I am struggling with it.

**Comment by linrongbin16** [comment]
emmmm, the code base is completely different, I don't think I could use it.

**Comment by linrongbin16** [comment]
hi @savchenko , I submit #627  to add 'FzfxMarks' command, it implements the `marks` command.

Would you please try it and give some feedbacks?

**Comment by linrongbin16** [comment]
Yes I am putting most of my time in rsvim now. 

But thanks to your attention, I may still spend some time to implement these commands.

I think it won't conflict with the rsvim project (at least for now).

**Comment by linrongbin16** [comment]
I just added the ":History:" equivalent command "FzfxCommandHistory".
Please give me any feedbacks about it.

**Comment by linrongbin16** [comment]
And I will move this issue to #749 , it lists all the missing commands in fzf.vim and fzf-lua.

Hope we could fill the big gap with them.
