### ISSUE TITLE
Invalid buffers list after change session

### ISSUE THREAD

**Issue by damanis** [linrongbin16/fzfx.nvim#528]
After load another session `FzfxBuffers` shows only one buffer. For example, `Telescope buffers` show all session buffers.
Used session maganer: [Possession](https://github.com/jedrzejboczar/possession.nvim)

**Comment by linrongbin16** [comment]
hi @damanis , it's late in night (in my timezone), I will look into it later.

**Comment by damanis** [comment]
@linrongbin16 ,
I just opened issue. Maybe I'll se it on weekend.

**Comment by linrongbin16** [comment]
hi @damanis, if this issue didn't happen before, just show up in recent days, then it could be introduced in #526.

To prove this thought, could you help try the previous tag 'v4.1.2'? it's the latest version before that PR.

**Comment by damanis** [comment]
@linrongbin16 
Confirm, `tagv4.1.2` works properly, show all buffers after load new session.

**Comment by linrongbin16** [comment]
hi @damanis , then it must be the PR's change, I will create one more data source, one is the old one (include the unload buffers), one is the PR's behavior (exclude the unload buffers).

**Comment by damanis** [comment]
@linrongbin16 
> one is the old one (include the unload buffers), one is the PR's behavior (exclude the unload buffers).

If I understand correctly, you will create two tags with different behavior? Why just not get buffers list in every call of FzfxBuffers?

**Comment by damanis** [comment]
> recommend users to specify version/tag when install this plugin

But in this case the features added after the tag will be unavailable.

**Comment by linrongbin16** [comment]
> > recommend users to specify version/tag when install this plugin
> 
> But in this case the features added after the tag will be unavailable.

I will upgrade the major version number (for example v4 - v5) when we have a break change.

only lazy.nvim support the semver, you can use `v4.*` to accept following updates in v4. and upgrade to v5 when you  want.

**Comment by damanis** [comment]
`4.1.2` has no buffers problem, `4.1.3` has one. If select `4.1.2`, so all changes in `4.1.{4-*}` will be unavailable, isn't it?

**Comment by linrongbin16** [comment]
> `4.1.2` has no buffers problem, `4.1.3` has one. If select `4.1.2`, so all changes in `4.1.{4-*}` will be unavailable, isn't it?

I think it's yes.

**Comment by damanis** [comment]
So, again, why just not get buffers list in every call of FzfxBuffers? It will solve both problem.
Or, maybe, nvim provides some additional event (`fzf-lua` and `telescope buffers` show proper list).

**Comment by linrongbin16** [comment]
hi @damanis, the fix pr is merged, please pull and try again.

**Comment by damanis** [comment]
@linrongbin16 
Confirmed.
Happy New Year!

**Comment by linrongbin16** [comment]
hi @savchenko, sorry previous #522 #526 is been reverted in #536, but I will create another variant buffers.
