### ISSUE TITLE
FeatureRequest: reduce live grep (buffer variant) filename

### ISSUE THREAD

**Issue by linrongbin16** [linrongbin16/fzfx.nvim#611]
https://github.com/linrongbin16/fzfx.nvim/discussions/435

**Comment by linrongbin16** [comment]
hi @damanis, sorry for being so late, I submit #620  to improve this feature.

**Comment by linrongbin16** [comment]
hi @damanis, I had add `FzfxBufLiveGrep` command for a **No Filename** live grep on current buffer in #622 . Please pull main branch and try!

**Comment by damanis** [comment]
Hi @linrongbin16 
This configuration works.
```
  { '<leader>xs', '<cmd>FzfxBufLiveGrep args<cr>' },
  { '<leader><Leader>xs', '<cmd>FzfxBufLiveGrep cword<cr>' },
```

P.S. I'm not sure it is right idea use `args` and `cword` instead of `buf_args` and `buf_cword`. Unification should be more correct.

**Comment by linrongbin16** [comment]
Hi @damanis, The command itself has `Buf`, no need to add it in sub commands.
