### ISSUE TITLE
esc cannot exist 

### ISSUE THREAD

**Issue by Jaehaks** [linrongbin16/fzfx.nvim#680]
i configure fzfx with default value.
but when i open any fzfx window, esc key operate only change mode from terminal to normal. not quit 

if i :q to quit. it said exit error code 143

**Comment by linrongbin16** [comment]
hi, will take a look

**Comment by linrongbin16** [comment]
hi @Jaehaks ,

I cannot reproduce this issue on my Windows 10 machine, would you please share a minimal init.lua that reproduce your issue?

![image](https://github.com/linrongbin16/fzfx.nvim/assets/6496887/92b02754-8874-463f-af75-3ed053d5f515)
