### ISSUE TITLE
win_opts = { relative = 'win' } is buggy

### ISSUE THREAD

**Issue by savchenko** [linrongbin16/fzfx.nvim#682]
Trying to understand the root cause of https://github.com/linrongbin16/fzfx.nvim/issues/603, I have found that `relative = 'win'` causes plugin to recursively reduce size of the popup when enabling/disabling the preview:

```lua
popup = {
    win_opts = {
        relative = 'win'
    }
}
```

It looks pretty wild :) See below:

https://github.com/linrongbin16/fzfx.nvim/assets/300146/e73b2081-560c-4fca-991c-d8b0b4c35f79

**Comment by linrongbin16** [comment]
hi @savchenko ,

I fixed this issue in #691 , please have a try!
