### ISSUE TITLE
Allow disabling the signcolumn and line numbers in pop-up window

### ISSUE THREAD

**Issue by savchenko** [linrongbin16/fzfx.nvim#684]
`:set scl=no` and `:set nonu` should do the trick.

Especially the signcolumn, as it doesn't seem to contribute much:

![image](https://github.com/linrongbin16/fzfx.nvim/assets/300146/e6b2b8df-83f8-487f-9811-b998aef32ebc)

**Comment by linrongbin16** [comment]
hi @savchenko ,

This feature is added in #690 , please have a try!
