### ISSUE TITLE
Error with buff on Windows11

### ISSUE THREAD

**Issue by DArt503** [linrongbin16/fzfx.nvim#74]
Hello, 

I would like to test your plugin (thanks for your work), I am on windows11, nvim 10 (nightly branch).

I get this error when launching FzxFiles command.
I am on windows11, nvim 10 (nightly branch).

![image](https://github.com/linrongbin16/fzfx.nvim/assets/32910847/14fbcb66-f147-4aef-8181-b28f56235b86)

**Comment by linrongbin16** [comment]
Hi, @DArt503 , checking.

**Comment by linrongbin16** [comment]
Hi @DArt503 , can you give me:

* `nvim --version`
* enter nvim and type: `:checkhealth`

**Comment by DArt503** [comment]
@linrongbin16 Here it is: 

nvim --version:

`NVIM v0.10.0-dev-741+g996dd36c7
Build type: RelWithDebInfo
LuaJIT 2.1.0-beta3
Run "nvim -V1 -v" for more info`

Checkhealth:

==============================================================================
floaterm: health#floaterm#check

common ~
- WARNING health#report_start is deprecated, use vim.health.start instead. :help |deprecated|
  This feature will be removed in Nvim version 0.11
- Platform: win
- WARNING health#report_info is deprecated, use vim.health.info instead. :help |deprecated|
  This feature will be removed in Nvim version 0.11
- Nvim: NVIM v0.10.0-dev-741+g996dd36c7
- Plugin: bcaeabf
  

terminal ~
- OK Terminal emulator is available
- WARNING health#report_ok is deprecated, use vim.health.ok instead. :help |deprecated|
  This feature will be removed in Nvim version 0.11

floating ~
- OK Floating window is available

==============================================================================
lazy: require("lazy.health").check()

lazy.nvim ~
- OK Git installed
- OK no existing packages found by other package managers
- OK packer_compiled.lua not found

==============================================================================
mason: require("mason.health").check()

mason.nvim ~
- OK mason.nvim version v1.6.2
- OK PATH: prepend
- OK Providers: 
    mason.providers.registry-api
    mason.providers.client
- OK neovim version >= 0.7.0

mason.nvim [Registries] ~

mason.nvim [Core utils] ~
- OK unzip: `UnZip 6.00 of 20 April 2009, by Info-ZIP.  Maintained by C. Spieler.  Send`
- OK wget: `GNU Wget 1.21.4 built on mingw32.
`
- OK curl: `curl 8.0.1 (Windows) libcurl/8.0.1 Schannel WinIDN
`
- OK gzip: `gzip 1.12`
- OK tar: `bsdtar 3.5.2 - libarchive 3.5.2 zlib/1.2.5.f-ipp bz2lib/1.0.6 
`
- OK pwsh: `7.3.6 Microsoft Windows 10.0.22621 Win32NT
`
- OK 7z: `7-Zip 9.10 beta  Copyright (c) 1999-2009 Igor Pavlov  2009-12-22
`

mason.nvim [Languages] ~
- WARNING Go: not available
  - ADVICE:
    - spawn: go failed with exit code - and signal -. go is not executable
- WARNING Composer: not available
  - ADVICE:
    - spawn: composer.bat failed with exit code - and signal -. composer.bat is not executable
- WARNING PHP: not available
  - ADVICE:
    - spawn: php failed with exit code - and signal -. php is not executable
- WARNING cargo: not available
  - ADVICE:
    - spawn: cargo failed with exit code - and signal -. cargo is not executable
- OK node: `v19.6.0
`
- WARNING javac: not available
  - ADVICE:
    - spawn: javac failed with exit code - and signal -. javac is not executable
- OK Ruby: `ruby 3.0.3p157 (2021-11-24 revision 3fb7d2cadc) [x64-mingw32]
`
- WARNING julia: not available
  - ADVICE:
    - spawn: julia failed with exit code - and signal -. julia is not executable
- WARNING luarocks: unsupported version `luarocks 2.0.2
`
  - ADVICE:
    - Luarocks version must be >= 3.0.0.
- OK python: `Python 3.11.0
`
- OK java: `openjdk version "19.0.2" 2023-01-17
`
- OK RubyGem: `3.2.32
`
- OK pip: `pip 23.0.1 from C:\Python311\Lib\site-packages\pip (python 3.11)

`
- OK python venv: `Ok`
- OK npm: `9.4.0`

mason.nvim [GitHub] ~
- OK GitHub API rate limit. Used: 0. Remaining: 5000. Limit: 5000. Reset: 17/08/2023 11:52:32.

==============================================================================
nvim: require("nvim.health").check()

Configuration ~
- OK no issues found

Runtime ~
- OK $VIMRUNTIME: C:\Program Files\Neovim\share\nvim\runtime

Performance ~
- OK Build type: RelWithDebInfo

Remote Plugins ~
- OK Up to date

terminal ~
- key_backspace (kbs) terminfo entry: `key_backspace=^H`
- key_dc (kdch1) terminfo entry: `key_dc=\E[3~`
- $COLORTERM="truecolor"

==============================================================================
nvim-treesitter: require("nvim-treesitter.health").check()

Installation ~
- WARNING `tree-sitter` executable not found (parser generator, only needed for :TSInstallFromGrammar, not required for :TSInstall)
- OK `node` found v19.6.0 (only needed for :TSInstallFromGrammar)
- OK `git` executable found.
- OK `gcc` executable found. Selected from { vim.NIL, "cc", "gcc", "clang", "cl", "zig" }
  Version: gcc.exe (x86_64-posix-seh-rev2, Built by MinGW-W64 project) 12.2.0
- OK Neovim was compiled with tree-sitter runtime ABI version 14 (required >=13). Parsers must be compatible with runtime ABI.

OS Info:
{
  machine = "x86_64",
  release = "10.0.22621",
  sysname = "Windows_NT",
  version = "Windows 11 Pro"
} ~

Parser/Features         H L F I J
  - bash                ✓ ✓ ✓ . ✓
  - c                   ✓ ✓ ✓ ✓ ✓
  - cpp                 ✓ ✓ ✓ ✓ ✓
  - lua                 ✓ ✓ ✓ ✓ ✓
  - markdown            ✓ . ✓ ✓ ✓
  - markdown_inline     ✓ . . . ✓
  - python              ✓ ✓ ✓ ✓ ✓
  - qmljs               ✓ . ✓ . .

  Legend: H[ighlight], L[ocals], F[olds], I[ndents], In[j]ections
         +) multiple parsers found, only one will be used
         x) errors found in the query, try to run :TSUpdate {lang} ~

==============================================================================
provider: require("provider.health").check()

Clipboard (optional) ~
- OK Clipboard tool found: win32yank

Python 3 provider (optional) ~
- `g:python3_host_prog` is not set.  Searching for python in the environment.
- Executable: C:\Python311\python.EXE
- Python version: 3.11.0
- pynvim version: 0.4.3
- OK Latest pynvim is installed.

Python virtualenv ~
- OK no $VIRTUAL_ENV

Ruby provider (optional) ~
- Ruby: ruby 3.0.3p157 (2021-11-24 revision 3fb7d2cadc) [x64-mingw32]
- WARNING `neovim-ruby-host` not found.
  - ADVICE:
    - Run `gem install neovim` to ensure the neovim RubyGem is installed.
    - Run `gem environment` to ensure the gem bin directory is in $PATH.
    - If you are using rvm/rbenv/chruby, try "rehashing".
    - See :help |g:ruby_host_prog| for non-standard gem installations.
    - You may disable this provider (and warning) by adding `let g:loaded_ruby_provider = 0` to your init.vim

Node.js provider (optional) ~
- Node.js: v19.6.0
- WARNING Missing "neovim" npm (or yarn, pnpm) package.
  - ADVICE:
    - Run in shell: npm install -g neovim
    - Run in shell (if you use yarn): yarn global add neovim
    - Run in shell (if you use pnpm): pnpm install -g neovim
    - You may disable this provider (and warning) by adding `let g:loaded_node_provider = 0` to your init.vim

Perl provider (optional) ~
- WARNING "Neovim::Ext" cpan module is not installed
  - ADVICE:
    - See :help |provider-perl| for more information.
    - You may disable this provider (and warning) by adding `let g:loaded_perl_provider = 0` to your init.vim

==============================================================================
telescope: require("telescope.health").check()

Checking for required plugins ~
- OK plenary installed.
- OK nvim-treesitter installed.

Checking external dependencies ~
- OK rg: found ripgrep 13.0.0 (rev af6b6c543b)
- OK fd: found fd 8.7.0

===== Installed extensions ===== ~

Telescope Extension: `lazygit` ~
- No healthcheck provided

Telescope Extension: `live_grep_args` ~
- No healthcheck provided

Telescope Extension: `refactoring` ~
- No healthcheck provided

Telescope Extension: `ui-select` ~
- No healthcheck provided

==============================================================================
vim.lsp: require("vim.lsp.health").check()

- LSP log level : WARN
- Log path: C:\Users\DArt\AppData\Local\nvim-data\lsp.log
- WARNING Log size: 336650 KB

vim.lsp: Active Clients ~
- No active clients

==============================================================================
vim.treesitter: require("vim.treesitter.health").check()

- Nvim runtime ABI version: 14
- OK Parser: bash       ABI: 14, path: C:\Users\DArt\AppData\Local\nvim-data\lazy\nvim-treesitter\parser\bash.so
- OK Parser: c          ABI: 14, path: C:\Users\DArt\AppData\Local\nvim-data\lazy\nvim-treesitter\parser\c.so
- OK Parser: cpp        ABI: 14, path: C:\Users\DArt\AppData\Local\nvim-data\lazy\nvim-treesitter\parser\cpp.so
- OK Parser: lua        ABI: 14, path: C:\Users\DArt\AppData\Local\nvim-data\lazy\nvim-treesitter\parser\lua.so
- OK Parser: markdown   ABI: 14, path: C:\Users\DArt\AppData\Local\nvim-data\lazy\nvim-treesitter\parser\markdown.so
- OK Parser: markdown_inline ABI: 14, path: C:\Users\DArt\AppData\Local\nvim-data\lazy\nvim-treesitter\parser\markdown_inline.so
- OK Parser: python     ABI: 14, path: C:\Users\DArt\AppData\Local\nvim-data\lazy\nvim-treesitter\parser\python.so
- OK Parser: qmljs      ABI: 14, path: C:\Users\DArt\AppData\Local\nvim-data\lazy\nvim-treesitter\parser\qmljs.so
- OK Parser: bash       ABI: 14, path: C:\Program Files\Neovim\lib\nvim\parser\bash.dll
- OK Parser: c          ABI: 14, path: C:\Program Files\Neovim\lib\nvim\parser\c.dll
- OK Parser: lua        ABI: 14, path: C:\Program Files\Neovim\lib\nvim\parser\lua.dll
- OK Parser: markdown   ABI: 14, path: C:\Program Files\Neovim\lib\nvim\parser\markdown.dll
- OK Parser: markdown_inline ABI: 14, path: C:\Program Files\Neovim\lib\nvim\parser\markdown_inline.dll
- OK Parser: python     ABI: 14, path: C:\Program Files\Neovim\lib\nvim\parser\python.dll
- OK Parser: query      ABI: 14, path: C:\Program Files\Neovim\lib\nvim\parser\query.dll
- OK Parser: vim        ABI: 14, path: C:\Program Files\Neovim\lib\nvim\parser\vim.dll
- OK Parser: vimdoc     ABI: 14, path: C:\Program Files\Neovim\lib\nvim\parser\vimdoc.dll

**Comment by linrongbin16** [comment]
I checked `spell` option doc: https://neovim.io/doc/user/options.html#'spell'
It looks `spell` becomes window-local option, I had thought it's a buffer-local option.

I'm using Neovim v0.9.1, and everything is going fine.

**Comment by linrongbin16** [comment]
@DArt503 ,

Can you try install this plugin with branch `linrongbin16/try-fix` ? and see if it work.

**Comment by linrongbin16** [comment]
OK, it looks like the Neovim API `vim.api.nvim_set_option_value` cannot accept either `buf` or `win` on 0.10-dev.

**Comment by DArt503** [comment]
@linrongbin16  With NVim 0.9.1, I get this one:
![image](https://github.com/linrongbin16/fzfx.nvim/assets/32910847/12455ef2-7b2b-48ae-9485-86d9bf24fee2)

(so same than the one with your test branch)

**Comment by linrongbin16** [comment]
@DArt503 ,

I also update the fix branch, removed the `nospell`, you can also try and see if it solved the issue.

**Comment by DArt503** [comment]
@linrongbin16 On NVim 0.9.1 with your last commit, it seems to open the window correctly but instantly close itself with that: 
![image](https://github.com/linrongbin16/fzfx.nvim/assets/32910847/90f5a864-03a7-4ecd-8275-6273368598a0)

Could it be a trouble with another plugin installed ?

**Comment by linrongbin16** [comment]
emmmm, can you try this init.lua:

```lua
vim.o.number = true
vim.o.autoread = true
vim.o.autowrite = true
vim.o.swapfile = false
vim.o.confirm = true
vim.o.termguicolors = true

local lazypath = vim.fn.stdpath("data") .. "/lazy/lazy.nvim"
if not vim.loop.fs_stat(lazypath) then
    vim.fn.system({
        "git",
        "clone",
        "--filter=blob:none",
        "https://github.com/folke/lazy.nvim.git",
        "--branch=stable", -- latest stable release
        lazypath,
    })
end
vim.opt.rtp:prepend(lazypath)

local opts = {
    defaults = { lazy = false },
}

require("lazy").setup({
    "folke/tokyonight.nvim",
    "nvim-tree/nvim-web-devicons",
    {
        "junegunn/fzf",
        build = ":call fzf#install()",
    },
    {
        "linrongbin16/fzfx.nvim",
        dev = true,
        dir = "~/github/linrongbin16/fzfx.nvim",
        opts = {},
        dependencies = {
            "folke/tokyonight.nvim",
            "nvim-tree/nvim-web-devicons",
            "junegunn/fzf",
        },
    },
}, opts)

require("lazy").sync({ wait = true, show = false })

vim.cmd([[
colorscheme tokyonight
]])

```

**Comment by linrongbin16** [comment]
@DArt503 , that's an assertion log, it usually indicates some error, I could move that log from `ERROR` to `DEBUG` so it will disappear.

**Comment by DArt503** [comment]
@linrongbin16 works correctly with your init.lua, so certainly something in my config, I will try to find what is it :)

**Comment by linrongbin16** [comment]
I depressed the error log, now it will be only an info message from console, should not disturbing you.

**Comment by linrongbin16** [comment]
Hi @DArt503 , do you have any other issues?

**Comment by DArt503** [comment]
Hi @linrongbin16, thx for your time :)

With NVim 0.10, I have still the error with spell (with a clean config with your init.lua above and fzfx at master) (same with my dev config).
With NVim 0.9.1, (same clean config), no error, it works correctly.
With NVim 0.9.1 and my dev config, windows open and still close.

So, I think there is an issue with 0.10.0 and something wrong with my dev setup. I will try to move plugin per plugin on the clean config+NVim 0.9.1 to find which one is causing the issue. :)

**Comment by DArt503** [comment]
The error in 0.9.1:
![image](https://github.com/linrongbin16/fzfx.nvim/assets/32910847/3c657482-80f8-4283-97fd-635c4a724625)

**Comment by DArt503** [comment]
@linrongbin16  Found !

That was this part used to have powershell as shell instead cmd:
`
if (vim.fn.has("win32") == 1) or (vim.fn.has("win64") == 1) then
	vim.opt.shell = "powershell.exe"
	vim.opt.shellxquote = ""
	vim.opt.shellcmdflag = "-NoLogo -NoProfile -ExecutionPolicy RemoteSigned -Command "
	vim.opt.shellquote = ""
	vim.opt.shellpipe = "| Out-File -Encoding UTF8 %s"
	vim.opt.shellredir = "| Out-File -Encoding UTF8 %s"
end
`

**Comment by DArt503** [comment]
Still same trouble with Neovim 0.10.0 but it works with 0.9.1

**Comment by linrongbin16** [comment]
Oh thanks @DArt503 , that's helping a lot!
I will try to check these options and make them compatible.

**Comment by linrongbin16** [comment]
The 'v:null` action key should be another warning message, I could depress it.

**Comment by DArt503** [comment]
@linrongbin16 ok!

It working correctly without the powershell trick, I still have an error while selecting a file:
![image](https://github.com/linrongbin16/fzfx.nvim/assets/32910847/cafd2fb9-de4f-4650-9935-24f8cbae292d)

Once acknowledge, file is opening as attended.

**Comment by linrongbin16** [comment]
I will fix this by save user's shell options before launching the fzf command, and restore these options after launching.

And force fzf command always running on `cmd.exe`.

**Comment by linrongbin16** [comment]
Hi @DArt503 , I fixed in https://github.com/linrongbin16/fzfx.nvim/pull/82, would you please pull again and try?

**Comment by DArt503** [comment]
@linrongbin16 Works great ! Thx you! 👍 

My last trouble is this one :

> @linrongbin16 ok!
> 
> It working correctly without the powershell trick, I still have an error while selecting a file: ![image](https://user-images.githubusercontent.com/32910847/261535822-cafd2fb9-de4f-4650-9935-24f8cbae292d.png)
> 
> Once acknowledge, file is opening as attended.

**Comment by linrongbin16** [comment]
Would you please:

1. Remove below two log files in `:stdpath('data')` directory (usually `C:\Users\YourName\AppData\Local\nivm-data`) if there's any:
   * `fzfx.log`
   * `fzfx_shell_helpers.log`.
1. Pull the latest main branch, and set this plugin config to `{ debug = { enable = true, file_log = true} }`.
3. Start neovim and run `:FzfxFiles`, select 1 file and press `enter`, if it fails, press `esc` to quit the plugin.
4. Upload the generated two log files in `:stdpath('data')` directory:
    * `fzfx.log`
    * `fzfx_shell_helpers.log`

**Comment by linrongbin16** [comment]
Hi @DArt503, I think I may missed one thing, what key do you press and generate this error? is that `enter` or `ctrl-t`, `ctrl-v`, `ctrl-x`?

**Comment by linrongbin16** [comment]
I had depressed the error message in https://github.com/linrongbin16/fzfx.nvim/pull/94, would you please pull latest main and try again?

**Comment by DArt503** [comment]
> Hi @DArt503, I think I may missed one thing, what key do you press and generate this error? is that `enter` or `ctrl-t`, `ctrl-v`, `ctrl-x`?

I used 'enter' :)

> I had depressed the error message in #94, would you please pull latest main and try again?

Works perfectly now ! thx

**Comment by AW3i** [comment]
When using neovim 0.10 nightly I also run into this problem on Linux, the plugin works perfectly in the 0.9 version.
```
Error executing Lua callback: ...aw3i/.local/share/nvim/lazy/fzfx.nvim/lua/fzfx/popup.lua:154: 'buf' cannot be passed for window-local option 'spell'
stack traceback:
        [C]: in function 'set_buf_option'
        ...aw3i/.local/share/nvim/lazy/fzfx.nvim/lua/fzfx/popup.lua:154: in function 'new'
        ...aw3i/.local/share/nvim/lazy/fzfx.nvim/lua/fzfx/popup.lua:273: in function 'new'
        ...aw3i/.local/share/nvim/lazy/fzfx.nvim/lua/fzfx/files.lua:119: in function <...aw3i/.local/share/nvim/lazy/fzfx.nvim/lua/fzfx/files.lua:27>
Error executing Lua callback: ...aw3i/.local/share/nvim/lazy/fzfx.nvim/lua/fzfx/popup.lua:154: 'buf' cannot be passed for window-local option 'spell'
stack traceback:
        [C]: in function 'set_buf_option'
        ...aw3i/.local/share/nvim/lazy/fzfx.nvim/lua/fzfx/popup.lua:154: in function 'new'
        ...aw3i/.local/share/nvim/lazy/fzfx.nvim/lua/fzfx/popup.lua:273: in function 'new'
        ...aw3i/.local/share/nvim/lazy/fzfx.nvim/lua/fzfx/files.lua:119: in function <...aw3i/.local/share/nvim/lazy/fzfx.nvim/lua/fzfx/files.lua:27>   
```

Neovim Version:
`
NVIM v0.10.0-dev-7c4d317
`
<details>
<summary> Check Health Output </summary>

```
Checking plugin dependencies ~
- OK nvim-web-devicons installed.

Checking VCS tools ~
- The plugin requires at least one of the supported VCS tools to be valid.
- OK Git found.
- OK Git is up-to-date. (2.41.0)
- WARNING Configured `hg_cmd` is not executable: 'hg'

==============================================================================
hydra: require("hydra.health").check()

- WARNING vim.health.report_start() is deprecated, use vim.health.start() instead. :help |deprecated|
  This feature will be removed in Nvim version 0.11

Hydra: Checking settings ~
- WARNING vim.health.report_ok() is deprecated, use vim.health.ok() instead. :help |deprecated|
  This feature will be removed in Nvim version 0.11
- OK             `timeoutlen` (value: 1000) is set to a good value.
          

==============================================================================
lazy: require("lazy.health").check()

lazy.nvim ~
- OK Git installed
- OK no existing packages found by other package managers
- OK packer_compiled.lua not found

==============================================================================
lspsaga: require("lspsaga.health").check()

Lspsaga.nvim report ~
- OK `tree-sitter` found 
- OK tree-sitter `markdown` parser found
- OK tree-sitter `markdown_inline` parser found

==============================================================================
mason: require("mason.health").check()

mason.nvim ~
- OK mason.nvim version v1.7.0
- OK PATH: prepend
- OK Providers: 
    mason.providers.registry-api
    mason.providers.client
- OK neovim version >= 0.7.0

mason.nvim [Registries] ~
- OK Registry `github.com/mason-org/mason-registry version: 2023-08-29-proper-lemon` is installed.

mason.nvim [Core utils] ~
- OK unzip: `UnZip 6.00 of 20 April 2009, by Info-ZIP.  Maintained by C. Spieler.  Send`
- OK wget: `GNU Wget 1.21.2 built on linux-gnu.`
- OK curl: `curl 7.81.0 (x86_64-pc-linux-gnu) libcurl/7.81.0 OpenSSL/3.0.2 zlib/1.2.11 brotli/1.0.9 zstd/1.4.8 libidn2/2.3.2 libpsl/0.21.0 (+libidn2/2.3.2) libssh/0.9.6/openssl/zlib nghttp2/1.43.0 librtmp/2.3 OpenLDAP/2.5.16`
- OK gzip: `gzip 1.10`
- OK tar: `tar (GNU tar) 1.34`
- OK bash: `GNU bash, version 5.1.16(1)-release (x86_64-pc-linux-gnu)`
- OK sh: `Ok`

mason.nvim [Languages] ~
- OK Go: `go version go1.20.7 linux/amd64`
- OK Ruby: `ruby 3.0.2p107 (2021-07-07 revision 0db68f0233) [x86_64-linux-gnu]`
- OK PHP: `PHP 8.1.22 (cli) (built: Aug 14 2023 05:32:33) (NTS)`
- OK cargo: `cargo 1.65.0-nightly (4ed54cecc 2022-08-27)`
- OK luarocks: `/nix/store/a2rxnmqvazc6hgdws01hvnyrwrgf94a3-luarocks-3.9.1/bin/.luarocks-wrapped 3.9.1`
- OK node: `v14.21.3`
- OK java: `openjdk version "17.0.8" 2023-07-18`
- WARNING julia: not available
  - ADVICE:
    - spawn: julia failed with exit code - and signal -. julia is not executable
- OK python: `Python 3.10.12`
- OK Composer: `Composer version 2.5.5 2023-03-21 11:50:05`
- OK javac: `javac 17.0.8`
- OK RubyGem: `3.3.5`
- OK npm: `6.14.18`
- OK pip: `pip 22.0.2 from /usr/lib/python3/dist-packages/pip (python 3.10)`
- OK python venv: `Ok`

mason.nvim [GitHub] ~
- OK GitHub API rate limit. Used: 0. Remaining: 60. Limit: 60. Reset: Tue 29 Aug 2023 01:29:19 PM EEST.
  Install and authenticate via gh-cli to increase rate limit.

==============================================================================
nvim: require("nvim.health").check()

Configuration ~
- OK no issues found

Runtime ~
- OK $VIMRUNTIME: /nix/store/gix16fyw4xx7wyl6j8710yiyjwi2c3dg-neovim-unwrapped-7c4d317/share/nvim/runtime

Performance ~
- OK Build type: Release

Remote Plugins ~
- OK Up to date

terminal ~
- key_backspace (kbs) terminfo entry: `key_backspace=\177`
- key_dc (kdch1) terminfo entry: `key_dc=\E[3~`
- $COLORTERM="truecolor"

==============================================================================
nvim-treesitter: require("nvim-treesitter.health").check()

Installation ~
- OK `tree-sitter` found 0.20.0 (e85a279cf29da1b08648e27214dda20a841e57c8) (parser generator, only needed for :TSInstallFromGrammar)
- OK `node` found v14.21.3 (only needed for :TSInstallFromGrammar)
- OK `git` executable found.
- OK `cc` executable found. Selected from { vim.NIL, "cc", "gcc", "clang", "cl", "zig" }
  Version: cc (Ubuntu 11.4.0-1ubuntu1~22.04) 11.4.0
- OK Neovim was compiled with tree-sitter runtime ABI version 14 (required >=13). Parsers must be compatible with runtime ABI.

OS Info:
{
  machine = "x86_64",
  release = "5.19.0-50-generic",
  sysname = "Linux",
  version = "#50-Ubuntu SMP PREEMPT_DYNAMIC Mon Jul 10 18:24:29 UTC 2023"
} ~

Parser/Features         H L F I J
  - c                   ✓ ✓ ✓ ✓ ✓
  - css                 ✓ . ✓ ✓ ✓
  - elixir              ✓ ✓ ✓ ✓ ✓
  - go                  ✓ ✓ ✓ ✓ ✓
  - graphql             ✓ . . ✓ ✓
  - html                ✓ ✓ ✓ ✓ ✓
  - javascript          ✓ ✓ ✓ ✓ ✓
  - jsdoc               ✓ . . . .
  - json                ✓ ✓ ✓ ✓ .
  - lua                 ✓ ✓ ✓ ✓ ✓
  - markdown            ✓ . ✓ ✓ ✓
  - markdown_inline     ✓ . . . ✓
  - php                 ✓ ✓ ✓ ✓ ✓
  - python              ✓ ✓ ✓ ✓ ✓
  - query               ✓ ✓ ✓ ✓ ✓
  - regex               ✓ . . . .
  - rust                ✓ ✓ ✓ ✓ ✓
  - typescript          ✓ ✓ ✓ ✓ ✓
  - vim                 ✓ ✓ ✓ . ✓
  - vimdoc              ✓ . . . ✓

  Legend: H[ighlight], L[ocals], F[olds], I[ndents], In[j]ections
         +) multiple parsers found, only one will be used

==============================================================================
provider: require("provider.health").check()

Clipboard (optional) ~
- OK Clipboard tool found: xsel

Python 3 provider (optional) ~
- Disabled (loaded_python3_provider=0).

Ruby provider (optional) ~
- Disabled (loaded_ruby_provider=0).

Node.js provider (optional) ~
- Disabled (loaded_node_provider=0).

Perl provider (optional) ~
- Disabled (loaded_perl_provider=0).

==============================================================================
vim.lsp: require("vim.lsp.health").check()

- LSP log level : WARN
- Log path: /home/aw3i/.local/state/nvim/lsp.log
- Log size: 4551 KB

vim.lsp: Active Clients ~
- No active clients
```

</details>

**Comment by linrongbin16** [comment]
Hi @AW3i, I start a discussion in upstream:
 https://github.com/neovim/neovim/discussions/24928

**Comment by linrongbin16** [comment]
In the source code, I use a new api after nvim-0.7, so maybe we can try to use the deprecated api (if it works).

I will test it today.

**Comment by linrongbin16** [comment]
Hi @AW3i & @DArt503 , I submit PR #114 to fix the set `spell=false` on wrong buffer number issue. Would you please pull latest main branch and try again?

**Comment by DArt503** [comment]
It is ok on my side with NVim 0.9.1 with last modification (no errors) @linrongbin16 !

**Comment by AW3i** [comment]
@linrongbin16 the spell error is gone in v0.10 but I'm getting a similar error with number now
```
Error executing Lua callback: ...aw3i/.local/share/nvim/lazy/fzfx.nvim/lua/fzfx/popup.lua:156: 'buf' cannot be passed for window-local option 'number'                                                          
stack traceback:                                                                                                                                                                                                
        [C]: in function 'set_buf_option'                                                                                                                                                                       
        ...aw3i/.local/share/nvim/lazy/fzfx.nvim/lua/fzfx/popup.lua:156: in function 'new'                                                                                                                      
        ...aw3i/.local/share/nvim/lazy/fzfx.nvim/lua/fzfx/popup.lua:274: in function 'new'                                                                                                                      
        ...aw3i/.local/share/nvim/lazy/fzfx.nvim/lua/fzfx/files.lua:119: in function <...aw3i/.local/share/nvim/lazy/fzfx.nvim/lua/fzfx/files.lua:27>
```

**Comment by linrongbin16** [comment]
@AW3i  turns out the `set number=false` is also related to window.

Fixed in #116 , please pull and try.

**Comment by AW3i** [comment]
It works now, thank you!

**Comment by linrongbin16** [comment]
finally close this issue!
