### ISSUE TITLE
Disable automatic theme creation

### ISSUE THREAD

**Issue by savchenko** [linrongbin16/fzfx.nvim#741]
I have observed a case where `fzfx` creates a theme for ViFM (!) automatically, in the directory where `:vifm` is called. No reproduction steps yet, as it happened twice and in uncertain circumstances.

Would it be possible to make automatic theme generation optional?

**Comment by linrongbin16** [comment]
yes, it's possible. I can add a switch to disable it.

**Comment by linrongbin16** [comment]
hi @savchenko , it's done in #743 , please pull and try!
