### ISSUE TITLE
Bug: Can't Close Popup Window with ESC Key

### ISSUE THREAD

**Issue by stong1994** [linrongbin16/fzfx.nvim#742]
When I press the ESC key to close the popup window, instead of closing, another window appears. This issue specifically occurs with the popup window generated by the fzfx.

Steps to reproduce:
1. Open the fzfx popup window with command(e.g., FzfxFiles).
2. Press the ESC key.
3. Observe that the popup does not close and another window is triggered.

Expected behavior:
- The popup window should close upon pressing the ESC key.

Actual behavior:
- The popup remains open and a new window is displayed.

<img width="2009" alt="image" src="https://github.com/user-attachments/assets/e4b9fdba-0897-46ef-95a6-79da8a640f18">

**Comment by linrongbin16** [comment]
the red part looks like which-key.nvim UI.

**Comment by stong1994** [comment]
OK，我放了一张gif, 在我打开Live Grep后，按esc来关闭窗口时，下边显示了另一个窗口（就是上面标红的那个）
![example](https://github.com/user-attachments/assets/d283559c-90d5-4217-811c-33258aecf079)

**Comment by stong1994** [comment]
我把日志打开了，当我按esc后，on_exit 没有被触发，可能是被什么拦截了
<img width="1273" alt="image" src="https://github.com/user-attachments/assets/b6779fe0-23bc-42ec-a14a-0ea4bc5579ff">

**Comment by linrongbin16** [comment]
hi @stong1994 ,

看了你发的gif动态图，底部的那个弹框，看起来真的很像 https://github.com/folke/which-key.nvim 这个plugin。

这是我在它 README 里的截图（注意看底部的那个 `<esc> close`，基本上一模一样）：

![image](https://github.com/user-attachments/assets/bcdcb692-8b80-4006-8f94-0b32636ad396)

**Comment by stong1994** [comment]
是的，确实是which-key造成的。我把which-key的版本切到2.1.0之后，这个问题解决了。但是很多插件都依赖which-key，所以我后边还得再看看。
感谢大佬指点！竟然一眼就看出问题来了👍
