### ISSUE TITLE
Error with Live Grep on Windows 11

### ISSUE THREAD

**Issue by Sawansunar56** [linrongbin16/fzfx.nvim#85]
Hi,

I was trying out your plugin because it has windows support, and I got it to work for almost everything except for live grep. 

To elaborate, when I run FzfxLiveGrep, it opens up the menu with a list of all the searches but, as soon as I type any character, it produces the error command failed.  

*Before pressing any character*
![Screenshot 2023-08-20 020138](https://github.com/linrongbin16/fzfx.nvim/assets/62794662/eb483980-7aa8-4fb0-94dc-a045fd48d8f3)

*After pressing any character*
![Screenshot 2023-08-20 020156](https://github.com/linrongbin16/fzfx.nvim/assets/62794662/296b00eb-73b7-4625-8ff0-fb735fb21def)
character*

I tried reinstalling it multiple times but nothing seems to suffice. 

Please help me on this one.

**Comment by linrongbin16** [comment]
hi @Sawansunar56,

would you please try this command:

```
sleep 0.1 && rg
```

and give me the output.

**Comment by linrongbin16** [comment]
Hi, @Sawansunar56,
you can set `live_grep.other_opts.onchange_reload_delay=nil`, it may be fixed.

**Comment by Sawansunar56** [comment]
> Hi, @Sawansunar56, you can set `live_grep.other_opts.onchange_reload_delay=nil`, it may be fixed.

@linrongbin16  Thank you for the help.

This command fixed my problem and now everything works. Also, just to be sure, I changed this value in the config file.

Is there a simple way, to just search current buffer. I seemed to cannot find anything related to it in the readme, it would be helpful for me. 

Also, I appreciate the good work.

**Comment by linrongbin16** [comment]
> This command fixed my problem and now everything works. Also, just to be sure, I changed this value in the config file.

It is correct. The root cause is that your Windows didn't have the `sleep` command. I will improve the readme doc to add a tutorial about how to install linux commands on Windows. (because this plugin heavily need many linux commands such as `mv`, `sleep`, `cp`) That is actually a dependency for Windows.

> Is there a simple way, to just search current buffer? I seemed to cannot find anything related to it in the readme, it would be helpful for me.

There's no way to only search on current buffer. I think we can simply use `/` and start searching?

**Comment by linrongbin16** [comment]
I also improved the README doc for Windows dependency in https://github.com/linrongbin16/fzfx.nvim/pull/86, please see: https://github.com/linrongbin16/fzfx.nvim#requirement

**Comment by Sawansunar56** [comment]
> I also improved the README doc for Windows dependency in #86, please see: https://github.com/linrongbin16/fzfx.nvim#requirement

Yeah, that would make things easier. Thanks for the quick reply.
